spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://ep-raspy-shadow-ao1mq3c3-pooler.c-2.ap-southeast-1.aws.neon.tech/missinglink?sslmode=require
    username: neondb_owner
    password: npg_NyconGWA67BY

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: khiredurgesh@gmail.com
    password: drmqdjdgphryhbsk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true





app:
  jwt:
    secret: mysupersecuresecretkeythatismorethan32characterslong
    expiration-ms: 86400000